namespace Stateless.Dot
{
    enum ShapeType
    {
        box,
        polygon,
        ellipse,
        circle,
        point,
        egg,
        triangle,
        plaintext,
        diamond,
        trapezium,
        parallelogram,
        house,
        pentagon,
        hexagon,
        septagon,
        octagon,
        doublecircle,
        doubleoctagon,
        tripleoctagon,
        invtriangle,
        invtrapezium,
        invhouse,
        Mdiamond,
        Msquare,
        Mcircle,
        Mrecord,
        rect,
        rectangle,
        none
    }
}